### ISSUE TITLE
Version info: ensure the top version is also included in the info.

### ISSUE THREAD

**Issue by ikreymer** [webrecorder/webrecorderplayer-electron#20]
The version stack includes all the dependencies, but not the 'top-level' version from `package.json`,
should include that too!

**Comment by atomotic** [comment]
from [process](https://electron.atom.io/docs/api/process/) object we can get version number of electron, chrome and node:

1. `process.versions.electron`
2. `process.versions.chrome`
3. `process.versions.node`
