### ISSUE TITLE
No horizontal scrollbar

### ISSUE THREAD

**Issue by yhancik** [webrecorder/webrecorderplayer-electron#27]
Webrecorder Player 1.0.3 on Windows (10) doesn't display horizontal scrollbar on pages that need it.

Screenshot: [https://i.imgpile.com/nn60JL.png](https://i.imgpile.com/nn60JL.png)

Here's a collection with two recordings of pages that are larger than screens, and therefore require horizontal scrolling: https://webrecorder.io/yhancik/horizontal-scrolling/test,avenue-by-nicolas-sassoon

You can view the original pages here
http://imal.org/yannick/large.html
http://linkcabinet.eu/ (this one will change in early june, though)

**Comment by m4rk3r** [comment]
Thanks for the report @yhancik, should be fixed in the [latest release](https://github.com/webrecorder/webrecorderplayer-electron/releases/tag/v1.0.4)!
