### ISSUE TITLE
Separate CDX File Support

### ISSUE THREAD

**Issue by Saklad5** [webrecorder/webrecorderplayer-electron#35]
For larger WARC files, such as those produced by recursing through a website with wget for archival purposes, it is common to have tens of thousands of records. This is extremely slow to index on demand, so reading preexisting [.cdx files](http://archive.org/web/researcher/cdx_file_format.php) would _massively_ improve launch times.

This could be implemented by reading identically-named .cdx files in the same directory as the WARC file being opened, or by allowing the user to select the file manually. CDX files are explicitly designed to be machine-parsable, so it shouldn’t be difficult to implement that part.

**Comment by ikreymer** [comment]
There is now an automated cache that is created (in the `_warc_cache` directory in the same place as the WARC) which caches the WR Player state, including the cdx. The cache is more than just the cdx, and allows for fast reloads of WARC files that have been loaded before.

You should be able to load previously opened WARCs pretty quickly with version 1.6.0 and up.
