### ISSUE TITLE
[Linux] desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [webrecorder/webrecorderplayer-electron#41]
The desktop file is lacking a `Categories=` entry in the `*.desktop` file.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).

Reference: https://github.com/AppImage/AppImageHub/issues/2

**Comment by probonopd** [comment]
Thanks for fixing this. If someone could be so friendly to ping me once a new release is available for download, I could include it in the AppImageHub central directory of available AppImages. Thank you.

**Comment by ikreymer** [comment]
@probonopd this has now been included in the latest release:
https://github.com/webrecorder/webrecorderplayer-electron/releases/tag/v1.0.6

**Comment by probonopd** [comment]
Thank you @ikreymer. However, the desktop file does not pass `desktop-file-validation`:
```
webrecorderplayer-electron.desktop: error: value "network;" for key "Categories" in group "Desktop Entry" contains an unregistered value "network"; values extending the format should start with "X-"

webrecorderplayer-electron.desktop: hint: value "network;" for key "Categories" in group "Desktop Entry" does not contain a registered main category; application might only show up in a "catch-all" section of the application menu
```

It should be `Categories=Network;` according to https://standards.freedesktop.org/menu-spec/latest/apa.html. Note the trailing semicolon.

Please fix the desktop file and make sure it passes desktop-file-validation`.
