### ISSUE TITLE
Drag-and-drop support

### ISSUE THREAD

**Issue by ticky** [webrecorder/webrecorderplayer-electron#46]
Currently, it is not possible to drag a `.warc.gz` file onto the webrecorder player window and have it open. It instead offers a prompt to “download” the file.

Allowing drag-and-drop would make the application feel much more like a native application!

**Comment by m4rk3r** [comment]
This is in the beta v1.1.1 and coming soon to the main release, thanks!

**Comment by ticky** [comment]
Oh, wonderful, thank you! :)

**Comment by m4rk3r** [comment]
Thanks again for the request, this is now officially released in [v1.6.0](https://github.com/webrecorder/webrecorderplayer-electron/releases/tag/v1.6.0). Cheers!
