### ISSUE TITLE
Downloading from Safari results in ".warc" not ".warc.gz" 

### ISSUE THREAD

**Issue by patshiu** [webrecorder/webrecorderplayer-electron#51]
Taken from Lozana's V&A User Tests. 
I can replicate this. 

> "8.1 Downloading collections in WR main app (bug?)
> – Anisa discovered that when downloading a collection from webrecorder.io in Safari, the default file that is downloaded is .warc and not .warc.gz. The resulting .warc file seemed to be dysfunctional because the Player app couldn’t index it and chocked on it, and then even trying to upload it back up into the main app wasn’t working. However, by right-clicking (or CMD+click) on the Download button in Safari, the downloaded file was actually .warc.gz, which worked fine in the Player app & online. This resulted in an initial problem when starting the session – for the first ten minutes or so of the test, we had to ask the researchers to look at the collections via the public webrecorder.io links. As soon as we figured out the issue and the fix, we were able to resume with the test as planned. It was strange that the Download button didn’t seem to work in Safari, while Chrome and Firefox were fine with these collections, so it’s unlikely the collections themselves were causing the issue."

**Comment by atomotic** [comment]
disabling "**Open safe file after downloading**" should keep the original file intact.

![](https://i.imgur.com/hij1Yha.png)

**Comment by ikreymer** [comment]
Made obsolete via webrecorder/webrecorder#627, now donwloading warcs with just .warc extension
