### ISSUE TITLE
Only metadata is shown

### ISSUE THREAD

**Issue by oschihin** [webrecorder/webrecorderplayer-electron#63]
I am trying to open warc files that are produced through our webarchiving (webcurator / heritrix). We use OpenWayback to display the content, and there it shows just fine. When I open the same warc files in webrecorderplayer, the bookmark list is built. Choosing a booking then just shows the metadata, not the content.

On choosing a bookmark, all that is shown (abbreviated) is:

```
via: https://www.bzgbs.ch/multimedia/mediothek/allgemeines/
hopsFromSeed: RLRL
fetchTimeMs: 210
outlink: http://www.ub.unibas.ch/ub-medizin/dienstleistungen/dokumentenlieferdienst/online-bestellformular/ L a/@href
outlink: https://www.thieme-connect.com/products/ejournals/journal/10.1055/s-00000159 L a/@href
outlink: http://www.pflege-wissenschaft.info/ L a/@href
outlink: https://www.bzgbs.ch/documents/11/Recherchen_Hochschulschriften.pdf L a/@href
outlink: http://www.zeitschrift-gesundheitsberufe.info/ L a/@href
outlink: https://www.bzgbs.ch/ausbildungen/pflege-fh/ L a/@href
outlink: https://www.bzgbs.ch/documents/141/Katalogrecherche_in_Swissbib_Orange.pdf L a/@href
outlink: http://econtent.hogrefe.com/loi/noc L a/@href
outlink: http://www.geschichte-der-pflege.info/ L a/@href
outlink: https://olat.bzgbs.ch/ L a/@href
....
```

I am pretty new to web archiving and wonder if this is an issue with our warc files. Our headers look like this:
```
WARC/0.18
WARC-Type: request
WARC-Target-URI: https://www.bzgbs.ch/multimedia/mediothek/e-medien/
WARC-Date: 2018-03-29T18:40:34Z
WARC-Concurrent-To: <urn:uuid:48b6ea79-8070-4324-856f-f0d35b25f34e>
WARC-Record-ID: <urn:uuid:6df462f8-6fac-4d97-b3e3-f8643152e445>
Content-Type: application/http; msgtype=request
Content-Length: 323

GET /multimedia/mediothek/e-medien/ HTTP/1.0
User-Agent: Mozilla/5.0 (compatible; heritrix/1.14.1 +http://yourwebsite.domain.com/)
From: youremail@yourdomain.com
Connection: close
Referer: https://www.bzgbs.ch/multimedia/mediothek/allgemeines/
Host: www.bzgbs.ch
Cookie: csrftoken=YOMSouE26sbPFNOT4zTb59ImbifTIdNZ



WARC/0.18
WARC-Type: metadata
WARC-Target-URI: https://www.bzgbs.ch/multimedia/mediothek/e-medien/
WARC-Date: 2018-03-29T18:40:34Z
WARC-Concurrent-To: <urn:uuid:48b6ea79-8070-4324-856f-f0d35b25f34e>
WARC-Record-ID: <urn:uuid:540b2abd-13b3-4924-aefd-5c72f49d553b>
Content-Type: text/anvl
Content-Length: 6200
```

Tested on both the newest versions of the player on linux and windows, the result is the same.

Appreciate any support

**Comment by N0taN3rd** [comment]
@oschihin thank you for letting us know about this issue. 

The bookmark you clicked on, it was for a URL contained in the problematic WARC correct?

From your description the player displayed the metadata record for one of the actual pages in the WARC.

Also are you able to share the WARC with us that is giving you issue so that we can reproduce this bug and expedite resolving this issue?

**Comment by oschihin** [comment]
@N0taN3rd thanks for your quick response. I uploaded one of our smallest files from an extranet-harvesting.

[IAH-20140401051926-00000-pdstavs09.warc.gz](https://github.com/webrecorder/webrecorderplayer-electron/files/2278689/IAH-20140401051926-00000-pdstavs09.warc.gz)
