### ISSUE TITLE
Annotations

### ISSUE THREAD

**Issue by edsu** [webrecorder/webrecorderplayer-electron#64]
It would be super useful if WebrecorderPlayer could display bookmark annotations if they are present in the WARC data. I can see that my annotation is in the warcinfo record's`json-metadata` but I don't seem to see it in the UI?

Oh, and a big thank you for continuing to make this project awesome!

**Comment by m4rk3r** [comment]
Hi @edsu! Yes, definitely, we're aiming to release the new UI in the player in early sept. Can send you a pre-release build if you'd like to try it out : )

and thanks to you for your support!

**Comment by edsu** [comment]
Sure if it's easy to send along that would be great. I'm ehs@pobox.com. I tried the 1.1.2 Beta and it looked like there was some great improvements in there, but I didn't see the annotation yet?

**Comment by m4rk3r** [comment]
Thanks again Ed, this is now available in [v1.6.0](https://github.com/webrecorder/webrecorderplayer-electron/issues/70)
