### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by fede220** [webrecorder/webrecorderplayer-electron#65]
Hi I'm request new feature for Webrecorder player electron: its possible add export in other format (example html with assets for view in browser)? I'm using web browser and can add this feature in Webrecorder player electron?

**Comment by m4rk3r** [comment]
Unfortunately we don't support this, and I'm not sure if we will, but you might be interested in some of our other utilities to do work like this, like [warcit](https://github.com/webrecorder/warcit) and [warcio](https://github.com/webrecorder/warcio)
