### ISSUE TITLE
Filename placeholder shown in interface

### ISSUE THREAD

**Issue by machawk1** [webrecorder/webrecorderplayer-electron#70]
When loading a WARC from my local filesystem, the main frame part of the interface says "This collection was automatically created from {filename}" with the template-like literal intact. Elsewhere in the interface (top frame, as pictured), the filename is available.

![screen shot 2018-10-22 at 2 10 33 pm](https://user-images.githubusercontent.com/2514780/47310197-6b1bd700-d604-11e8-81fa-ca16e8763606.png)

webrecorder player 1.5.0
webrecorder_player 4.1.1 (@9c8e334)
pywb 2.0.5 (@71c3eb7) 
electron 1.8.7
chrome 59.0.3071.115

**Comment by ikreymer** [comment]
This has been fixed in 1.6.0. You should also see some additional metadata added to the description for non-Webrecorder WARCs.
